name: C/C++ CI self-hosted

on:
  push:
    paths: [ '**.c', '**.h', '**.m4', '**.sh', '.github/**', '**/Makefile.in', 'configure.ac' ]

jobs:
  selfhosted:
    if: github.repository == 'openssh/openssh-portable-selfhosted'
    runs-on: ${{ matrix.target }}
    timeout-minutes: 600
    env:
      TARGET_TYPE: ${{ matrix.type }}
      TARGET_HOST: ${{ matrix.target }}
    strategy:
      fail-fast: false
      # We use a matrix in two parts: firstly all of the VMs are tested with the
      # default config.  "target" corresponds to a label associated with the
      # worker.
      matrix:
        target:
          - aix51
          - ARM
          - ARM64
          - alpine
          - debian-i386
          - debian-riscv64
          - dfly30
          - dfly48
          - dfly58
          - dfly60
          - dfly62
          - fbsd10
          - fbsd12
          - fbsd13
          - minix3
          - nbsd3
          - nbsd4
          - nbsd8
          - nbsd9
          - obsd51
          - obsd67
          - obsd69
          - obsd70
          - obsdsnap
          - openindiana
          - openwrt-mips
          - openwrt-mipsel
          - sol10
          - sol11
          - win10
        configs:
          - default
        # Then we include any extra configs we want to test for specific VMs.
        include:
          - { target: ARM64,  configs: pam }
          - { target: debian-i386, configs: pam }
          - { target: dfly30, configs: default, type: libvirt }
          - { target: dfly30, configs: without-openssl}
          - { target: dfly48, configs: pam }
          - { target: dfly58, configs: pam }
          - { target: dfly60, configs: pam }
          - { target: dfly62, configs: pam }
          - { target: fbsd10, configs: pam }
          - { target: fbsd12, configs: pam }
          - { target: fbsd13, configs: pam }
          - { target: nbsd8,  configs: pam }
          - { target: nbsd9,  configs: pam }
          - { target: openindiana, configs: pam }
          - { target: sol10,  configs: pam }
          - { target: sol11,  configs: pam-krb5 }
          - { target: sol11,  configs: sol64 }
          - { target: win10,  configs: cygwin-release }
    steps:
    - name: shutdown VM if running
      run: vmshutdown
      working-directory: ${{ runner.temp }}
    - uses: actions/checkout@main
    - name: autoreconf
      run: autoreconf
    - name: startup VM
      run: vmstartup
    - name: configure
      run: vmrun ./.github/configure.sh ${{ matrix.configs }}
    - name: save config
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.target }}-${{ matrix.configs }}-config
        path: config.h
    - name: make clean
      run: vmrun make clean
    - name: make
      run: vmrun make
    - name: make tests
      run: vmrun ./.github/run_test.sh ${{ matrix.configs }}
      timeout-minutes: 600
    - name: save logs
      if: failure()
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.target }}-${{ matrix.configs }}-logs
        path: |
          config.h
          config.log
          regress/*.log
          regress/valgrind-out/
    - name: shutdown VM
      if: always()
      run: vmshutdown
      working-directory: ${{ runner.temp }}
